// Auto-generated by scripts/build-workflows.mjs — do not edit by hand.
//
// Creates every tab this project needs, with exact headers.
// In your Google Sheet: Extensions -> Apps Script, paste this, press Run,
// and approve the one-time permission prompt.

var TABS = {
  "Queue": [
    "job_id",
    "date_found",
    "title",
    "company",
    "domain",
    "location",
    "is_remote",
    "url",
    "match_score",
    "ats_score",
    "verdict",
    "matched_skills",
    "ats_missing",
    "ats_note",
    "reasoning",
    "recruiter_name",
    "recruiter_email",
    "recruiter_title",
    "contact_source",
    "subject",
    "cover_letter",
    "status",
    "sent_at",
    "notes"
  ],
  "Contacts": [
    "domain",
    "company",
    "recruiter_name",
    "recruiter_email",
    "recruiter_title",
    "found_at"
  ],
  "Skipped": [
    "date_found",
    "job_id",
    "title",
    "company",
    "url",
    "match_score",
    "reason"
  ],
  "Meta": [
    "key",
    "value"
  ]
};

function setUpJobsSheet() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();

  Object.keys(TABS).forEach(function (name) {
    var headers = TABS[name];
    var sheet = ss.getSheetByName(name) || ss.insertSheet(name);

    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
    sheet.getRange(1, 1, 1, headers.length).setFontWeight('bold');
    sheet.setFrozenRows(1);

    // Trim stray columns so the Sheets node doesn't see blank headers.
    var extra = sheet.getMaxColumns() - headers.length;
    if (extra > 0) sheet.deleteColumns(headers.length + 1, extra);
  });

  // Remove the default empty sheet if it is still untouched.
  var def = ss.getSheetByName('Sheet1');
  if (def && ss.getSheets().length > 1 && def.getLastRow() === 0) ss.deleteSheet(def);

  SpreadsheetApp.getUi().alert('Done — ' + Object.keys(TABS).join(', ') + ' are ready.');
}
